### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by downquark7** [jasonrahm/vvapp#1]
Hi,
I cloned the repository to use it, however I can't figure out how to initialize the db or create a user. It would be helpful to get more specific instructions. I am running Windows 10 if that changes the instructions at all.

**Comment by jasonrahm** [comment]
I'll be in the code tonight, I'll make sure to add a method to create an admin user at initialization, and I'll get instructions to create the db as well. Prepping for competition on Saturday, but will try to help you out.

**Comment by jasonrahm** [comment]
Once all your dependencies are installed, you should be able to create the database from cli in the app directory with:

python manage.py db init
python manage.py db migrate
python manage.py db upgrade

Then, to create your user, you can do that from python shell:

```
>>> from models import Users
>>> from app import bcrypt
>>> new_user = Users(email='test@local', password_hash=bcrypt.generate_password_hash('badpassword'))
>>> from app import db
>>> db.session.add(new_user)
>>> db.session.commit()
```

Finally, you can verify your user was added by opening sqlite database and running a query:

sqlite> select * from Users;
1|test@local|$2b$12$AgXsyGQJYirAFmxNb32QS.1chkVLT/94d4ttruZRSHx21suf74RJi|||1|2017-03-01 18:33:05.427283

Then just do "python run.py" at the command line in app directory and you should be able to log in at that point. I will work up some documentation next week.

**Comment by downquark7** [comment]
I tried to follow the instructions provided. Here is the output I got. I used the command py -2 because I have python3 installed. Is it possible I ran into errors because I installed the latest versions of the dependencies?

C:\Users\mail2\Documents\GitHub\vvapp\app>py -2 manage.py db init
Traceback (most recent call last):
  File "manage.py", line 2, in <module>
    from run import *
  File "C:\Users\mail2\Documents\GitHub\vvapp\app\run.py", line 1, in <module>
    from views import app
  File "C:\Users\mail2\Documents\GitHub\vvapp\app\views.py", line 38, in <module>
    Competitions.date == today).first()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 2731, in first
    ret = list(self[0:1])
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 2523, in __getitem__
    return list(res)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 2831, in __iter__
    return self._execute_and_instances(context)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 2854, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\sql\elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1189, in _execute_context
    context)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "C:\Python27\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
    context)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: Competitions [SQL: u'SELECT "Competitions".id AS "Competitions_id", "Competitions".name AS "Competitions_name", "Competitions".date AS "Competitions_date", "Competitions".created_timestamp AS "Competitions_created_timestamp", "Competitions".modified_timestamp AS "Competitions_modified_timestamp" \nFROM "Competitions" \nWHERE "Competitions".date = ?\n LIMIT ? OFFSET ?'] [parameters: ('2017-03-01', 1, 0)]

**Comment by jasonrahm** [comment]
I haven't developed for python 3 at all, so 2.7 would likely be necessary. It appears as though the database has not yet been completely setup, as it cannot find the Competitions table.

**Comment by downquark7** [comment]
I was able to make it work for me by changing the line in views.py where it looks for the table.

`try:
    compcheck = db.session.query(Competitions).filter(
        Competitions.date == today).first()
except:
    compcheck = None
    print "Logging a message here to signal that an exception was thrown when finding the table"`
